select 
  TABLE_NAME, 
  COLUMN_NAME, 
  DATA_TYPE, 
  CAST(NULL AS VARCHAR2(4)) 
  DATA_DEFAULT, 
  NULLABLE, 
  CAST(NULL AS VARCHAR2(4)) DATA_PRECISION, 
  CAST(NULL AS VARCHAR2(4)) DATA_SCALE,
  CAST(NULL AS VARCHAR2(4)) DATA_LENGTH 
from user_tab_columns 
where table_name = ? 